import React, { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { 
    Download, 
    ArrowLeft, 
    FileJson, 
    Loader2,
    FileText,
    Type,
    AlignLeft,
    AlignJustify,
    Minus,
    Plus,
    Edit3,
    Check,
    Palette,
    Save,
    RotateCcw
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import DashboardHeader from '@/components/DashboardHeader';
import ResumePreviewTemplate from '@/components/ResumePreviewTemplate';
import html2pdf from 'html2pdf.js';
import Editor from 'react-simple-wysiwyg';

const RAW_URL_BASE = 'https://raw.githubusercontent.com/jsonresume/jsonresume-fake/master/resumes';

const COLORS = [
    '#1f2937', // Gray
    '#2563eb', // Blue
    '#059669', // Emerald
    '#7c3aed', // Violet
    '#db2777', // Pink
    '#dc2626', // Red
];

const ResumeDetailsPage = () => {
    const { id } = useParams();
    const navigate = useNavigate();
    const [resumeData, setResumeData] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);
    const previewRef = useRef();
    
    // Customization State
    const [settings, setSettings] = useState({
        fontFamily: 'font-serif',
        fontSize: 'text-sm',
        accentColor: '#1f2937',
        lineHeight: 'leading-relaxed',
        textAlign: 'text-left'
    });

    // Editor State
    const [isEditing, setIsEditing] = useState(false);
    const [htmlContent, setHtmlContent] = useState(null);

    useEffect(() => {
        const fetchResume = async () => {
            try {
                setLoading(true);
                const response = await fetch(`${RAW_URL_BASE}/${id}`);
                if (!response.ok) throw new Error('Failed to load resume data');
                const text = await response.text();
                try {
                    const json = JSON.parse(text);
                    setResumeData(json);
                } catch (e) {
                    throw new Error('Invalid JSON format');
                }
            } catch (err) {
                console.error(err);
                setError(err.message);
            } finally {
                setLoading(false);
            }
        };

        if (id) {
            fetchResume();
        }
    }, [id]);

    const updateSetting = (key, value) => {
        setSettings(prev => ({ ...prev, [key]: value }));
    };

    const handleEditToggle = () => {
        if (!isEditing) {
            // If entering edit mode and we don't have custom content yet, capture it from preview
            if (!htmlContent && previewRef.current) {
                setHtmlContent(previewRef.current.innerHTML);
            }
            setIsEditing(true);
        } else {
            // Saving/Exiting edit mode
            setIsEditing(false);
        }
    };

    const downloadPDF = () => {
        const opt = {
             margin:       0,
             filename:     `${id?.replace('.json', '') || 'resume'}.pdf`,
             image:        { type: 'jpeg', quality: 0.98 },
             html2canvas:  { scale: 2, useCORS: true },
             jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
        };

        if (htmlContent) {
            // If we have custom HTML content (either currently editing or saved state)
            const printContainer = document.createElement('div');
            // Reconstruct the container with all the styles
            printContainer.innerHTML = htmlContent;
            printContainer.className = `bg-[#ffffff] text-[#000000] p-10 w-[816px] mx-auto shadow-2xl ${settings.fontSize} ${settings.fontFamily} ${settings.lineHeight} ${settings.textAlign}`;
            // We need to ensure styles (like color) that might be reliant on settings are applied. 
            // Note: innerHTML capture includes inline styles generated by ResumePreviewTemplate, so accentColors usually persist.
            
            printContainer.style.position = 'absolute';
            printContainer.style.left = '-9999px';
            document.body.appendChild(printContainer);
            
            html2pdf().set(opt).from(printContainer).save().then(() => {
                document.body.removeChild(printContainer);
            });
        } else if (previewRef.current) {
            // Standard preview mode
            html2pdf().set(opt).from(previewRef.current).save();
        }
    };

    const downloadJSON = () => {
        const url = `${RAW_URL_BASE}/${id}`;
        window.open(url, '_blank');
    };

    if (loading) {
        return (
            <div className="min-h-screen bg-[#0B0F1A] flex items-center justify-center">
                <Loader2 className="w-8 h-8 text-emerald-500 animate-spin" />
            </div>
        );
    }

    if (error) {
        return (
            <div className="min-h-screen bg-[#0B0F1A] flex flex-col items-center justify-center text-white">
                <p className="text-red-400 mb-4">Error: {error}</p>
                <Button variant="outline" onClick={() => navigate('/dashboard/resumes')}>
                    Back to Library
                </Button>
            </div>
        );
    }

    // Common container classes for consistency across renders
    const containerClasses = `bg-[#ffffff] text-[#000000] p-5 md:p-10 min-h-[60vh] md:min-h-[1056px] w-full max-w-[816px] mx-auto shadow-2xl ${settings.fontSize} ${settings.fontFamily} ${settings.lineHeight} ${settings.textAlign} relative outline-none`;

    return (
        <div className="min-h-screen bg-[#0B0F1A] text-foreground font-sans flex flex-col">
            <DashboardHeader />

            <main className="flex-1 pt-20 md:pt-24 pb-12 px-3 md:px-8 max-w-[1600px] mx-auto w-full">
                
                {/* Header Toolbar */}
                <motion.div 
                    initial={{ opacity: 0, y: -20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="flex flex-col md:flex-row justify-between items-start md:items-center bg-[#131722]/90 backdrop-blur-xl border border-white/10 p-4 rounded-xl mb-6 sticky top-20 z-30 shadow-2xl gap-4"
                >
                    <div className="flex items-center gap-4 w-full md:w-auto">
                        <Button 
                            variant="ghost" 
                            size="icon" 
                            onClick={() => navigate('/dashboard/resumes')}
                            className="text-muted-foreground hover:text-white hover:bg-white/5 rounded-full shrink-0"
                        >
                            <ArrowLeft className="w-5 h-5" />
                        </Button>
                        <div className="min-w-0">
                            <h1 className="text-lg font-bold text-white flex items-center gap-2 truncate">
                                <FileText className="w-5 h-5 text-emerald-500 shrink-0" />
                                <span className="truncate">{id?.replace(/-/g, ' ').replace('.json', '')}</span>
                            </h1>
                            <p className="text-xs text-muted-foreground">Resume Preview</p>
                        </div>
                    </div>

                    <div className="flex items-center gap-3 w-full md:w-auto grid grid-cols-2 md:flex">
                        <Button 
                            variant="outline" 
                            size="sm" 
                            onClick={downloadJSON}
                            className="border-white/10 hover:bg-white/5 text-white bg-transparent w-full md:w-auto"
                        >
                            <FileJson className="w-4 h-4 mr-2" /> 
                            <span className="hidden sm:inline">JSON Source</span>
                            <span className="sm:hidden">JSON</span>
                        </Button>
                        <Button 
                            size="sm" 
                            onClick={downloadPDF}
                            className="bg-emerald-600 hover:bg-emerald-500 text-white shadow-lg shadow-emerald-500/20 w-full md:w-auto"
                        >
                            <Download className="w-4 h-4 mr-2" /> 
                            <span className="hidden sm:inline">Download PDF</span>
                            <span className="sm:hidden">Save PDF</span>
                        </Button>
                    </div>
                </motion.div>

                {/* Customization & Editor Toolbar */}
                <motion.div 
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.1 }}
                    className="flex flex-nowrap items-center gap-3 bg-[#1a1f2e] border border-white/10 p-2 md:p-3 rounded-xl mb-6 shadow-xl sticky top-[8.5rem] z-20 mx-auto w-full max-w-[850px] overflow-x-auto no-scrollbar"
                >
                    {isEditing ? (
                        <div className="flex items-center gap-3 w-full min-w-max">
                            <span className="text-sm font-medium text-emerald-400 flex items-center gap-2 px-2">
                                <Edit3 className="w-4 h-4" /> Editing Mode
                            </span>
                             <div className="ml-auto flex items-center gap-2">
                                <AlertDialog>
                                    <AlertDialogTrigger asChild>
                                        <Button 
                                            size="sm"
                                            variant="outline"
                                            className="text-red-400 border-red-900/50 hover:bg-red-900/20 gap-2"
                                        >
                                            <RotateCcw className="w-4 h-4" /> <span className="hidden sm:inline">Reset</span>
                                        </Button>
                                    </AlertDialogTrigger>
                                    <AlertDialogContent className="bg-[#1a1f2e] border-white/10 text-white">
                                        <AlertDialogHeader>
                                            <AlertDialogTitle>Revert to Original?</AlertDialogTitle>
                                            <AlertDialogDescription className="text-gray-400">
                                                This will discard all your text edits and restore the original resume data. This action cannot be undone.
                                            </AlertDialogDescription>
                                        </AlertDialogHeader>
                                        <AlertDialogFooter>
                                            <AlertDialogCancel className="bg-transparent text-white border-white/10 hover:bg-white/5 hover:text-white">Cancel</AlertDialogCancel>
                                            <AlertDialogAction 
                                                onClick={() => { setHtmlContent(null); setIsEditing(false); }}
                                                className="bg-red-600 hover:bg-red-700 text-white border-none"
                                            >
                                                Reset Everything
                                            </AlertDialogAction>
                                        </AlertDialogFooter>
                                    </AlertDialogContent>
                                </AlertDialog>

                                <Button 
                                    size="sm"
                                    onClick={handleEditToggle} 
                                    className="bg-emerald-600 hover:bg-emerald-500 text-white gap-2"
                                >
                                    <Save className="w-4 h-4" /> Save <span className="hidden sm:inline">& View</span>
                                </Button>
                            </div>
                        </div>
                    ) : (
                        <>
                            {/* Font Family */}
                            <div className="flex items-center gap-1 bg-black/20 rounded-lg p-1 shrink-0">
                                <div className="flex flex-col gap-0.5 px-2">
                                    <span className="text-[10px] text-muted-foreground uppercase font-bold tracking-wider">Font</span>
                                </div>
                                <div className="h-6 w-px bg-white/10 mx-1" />
                                <Button title="Serif" variant={settings.fontFamily === 'font-serif' ? 'secondary' : 'ghost'} size="icon" onClick={() => updateSetting('fontFamily', 'font-serif')} className="h-8 w-8 text-white"><span className="font-serif text-lg">T</span></Button>
                                <Button title="Sans" variant={settings.fontFamily === 'font-sans' ? 'secondary' : 'ghost'} size="icon" onClick={() => updateSetting('fontFamily', 'font-sans')} className="h-8 w-8 text-white"><span className="font-sans text-lg">T</span></Button>
                            </div>

                            {/* Font Size */}
                            <div className="flex items-center gap-1 bg-black/20 rounded-lg p-1 shrink-0">
                                <div className="flex flex-col gap-0.5 px-2">
                                    <span className="text-[10px] text-muted-foreground uppercase font-bold tracking-wider">Size</span>
                                </div>
                                <div className="h-6 w-px bg-white/10 mx-1" />
                                <Button 
                                    variant="ghost" size="icon" 
                                    onClick={() => updateSetting('fontSize', settings.fontSize === 'text-sm' ? 'text-xs' : settings.fontSize === 'text-base' ? 'text-sm' : 'text-xs')} 
                                    className="h-8 w-8 text-white"
                                    disabled={settings.fontSize === 'text-xs'}
                                >
                                    <Minus className="w-3 h-3" />
                                </Button>
                                <span className="text-xs font-mono w-8 text-center text-white">
                                    {settings.fontSize === 'text-xs' ? 'XS' : settings.fontSize === 'text-sm' ? 'SM' : 'MD'}
                                </span>
                                <Button 
                                    variant="ghost" size="icon" 
                                    onClick={() => updateSetting('fontSize', settings.fontSize === 'text-xs' ? 'text-sm' : settings.fontSize === 'text-sm' ? 'text-base' : 'text-base')} 
                                    className="h-8 w-8 text-white"
                                    disabled={settings.fontSize === 'text-base'}
                                >
                                    <Plus className="w-3 h-3" />
                                </Button>
                            </div>

                             {/* Alignment */}
                             <div className="flex items-center gap-1 bg-black/20 rounded-lg p-1 shrink-0">
                                <Button variant={settings.textAlign === 'text-left' ? 'secondary' : 'ghost'} size="icon" onClick={() => updateSetting('textAlign', 'text-left')} className="h-8 w-8 text-white"><AlignLeft className="w-4 h-4" /></Button>
                                <Button variant={settings.textAlign === 'text-justify' ? 'secondary' : 'ghost'} size="icon" onClick={() => updateSetting('textAlign', 'text-justify')} className="h-8 w-8 text-white"><AlignJustify className="w-4 h-4" /></Button>
                            </div>

                            {/* Colors */}
                            <div className="flex items-center gap-2 bg-black/20 rounded-lg p-2 shrink-0">
                                <Palette className="w-4 h-4 text-muted-foreground mr-1" />
                                {COLORS.map(color => (
                                    <button
                                        key={color}
                                        onClick={() => updateSetting('accentColor', color)}
                                        className={`w-5 h-5 rounded-full transition-transform hover:scale-110 ${settings.accentColor === color ? 'ring-2 ring-white ring-offset-2 ring-offset-black scale-110' : ''}`}
                                        style={{ backgroundColor: color }}
                                    />
                                ))}
                            </div>

                            {/* Editor Controls */}
                            <div className="md:ml-auto pl-4 border-l border-white/10 shrink-0 flex items-center gap-2">
                                {htmlContent && (
                                    <AlertDialog>
                                        <AlertDialogTrigger asChild>
                                            <Button 
                                                variant="ghost" 
                                                size="sm"
                                                className="text-red-400 hover:bg-white/5"
                                                title="Revert to original"
                                            >
                                                <RotateCcw className="w-4 h-4" />
                                            </Button>
                                        </AlertDialogTrigger>
                                        <AlertDialogContent className="bg-[#1a1f2e] border-white/10 text-white">
                                            <AlertDialogHeader>
                                                <AlertDialogTitle>Revert to Original?</AlertDialogTitle>
                                                <AlertDialogDescription className="text-gray-400">
                                                    This will discard all your text edits and restore the original resume data. This action cannot be undone.
                                                </AlertDialogDescription>
                                            </AlertDialogHeader>
                                            <AlertDialogFooter>
                                                <AlertDialogCancel className="bg-transparent text-white border-white/10 hover:bg-white/5 hover:text-white">Cancel</AlertDialogCancel>
                                                <AlertDialogAction 
                                                    onClick={() => { setHtmlContent(null); setIsEditing(false); }}
                                                    className="bg-red-600 hover:bg-red-700 text-white border-none"
                                                >
                                                    Reset Everything
                                                </AlertDialogAction>
                                            </AlertDialogFooter>
                                        </AlertDialogContent>
                                    </AlertDialog>
                                )}
                                <Button 
                                    variant="outline" 
                                    size="sm"
                                    onClick={handleEditToggle} 
                                    className="text-white border-white/10 hover:bg-white/5 gap-2"
                                >
                                    <Edit3 className="w-4 h-4" /> {htmlContent ? 'Edit' : 'Edit Text'}
                                </Button>
                            </div>
                        </>
                    )}
                </motion.div>

                {/* Document Viewer Area */}
                <div className="flex justify-center w-full px-0 md:px-4">
                    <motion.div 
                        layout
                        className="w-full max-w-[850px] relative"
                    >
                        {/* Desktop Glow */}
                        <div className="hidden md:block absolute inset-0 bg-emerald-500/10 blur-3xl -z-10 rounded-full opacity-20" />
                        
                        <div 
                            className={`bg-white shadow-[0_0_50px_-12px_rgba(0,0,0,0.5)] rounded-sm overflow-hidden md:min-h-[1100px] w-full border-t-4 transition-colors duration-500`}
                            style={{ borderColor: settings.accentColor }}
                        >
                            {isEditing ? (
                                <div className={`${containerClasses.replace('shadow-2xl', '').replace('p-5 md:p-10', '')} !shadow-none !p-0 !min-h-0`}>
                                     {/* 
                                        React Simple WYSIWYG Editor 
                                        - containerProps: Wrapper styles (Toolbar placement)
                                        - className/style: Content styles (Resume look)
                                     */}
                                     <Editor 
                                        value={htmlContent || ''} 
                                        onChange={(e) => setHtmlContent(e.target.value)}
                                        containerProps={{ 
                                            style: { 
                                                minHeight: '1056px',
                                                display: 'flex',
                                                flexDirection: 'column',
                                                backgroundColor: '#ffffff',
                                                color: '#000000',
                                            },
                                        }}
                                        className={`outline-none flex-1 p-5 md:p-10 ${settings.fontSize} ${settings.fontFamily} ${settings.lineHeight} ${settings.textAlign}`}
                                        style={{
                                            // Ensure the content area takes up space and mimics the page
                                            flexGrow: 1,
                                            textAlign: settings.textAlign === 'text-justify' ? 'justify' : 'left'
                                        }}
                                     />
                                </div>
                            ) : htmlContent ? (
                                <div 
                                    className={`${containerClasses.replace('shadow-2xl', '')} p-5 md:p-10`} // Remove shadow here as it is on parent
                                    style={{ color: '#000000' }}
                                    dangerouslySetInnerHTML={{ __html: htmlContent }}
                                />
                            ) : (
                                <div className="p-5 md:p-10">
                                    <ResumePreviewTemplate 
                                        ref={previewRef} 
                                        data={resumeData} 
                                        settings={settings}
                                    />
                                </div>
                            )}
                        </div>

                         <div className="text-center mt-8 text-muted-foreground text-xs pb-8 md:pb-0">
                             {isEditing ? 'Editing Mode Active - Changes are local' : 'Preview generated by SkillSynx Resume Engine'}
                        </div>
                    </motion.div>
                </div>

            </main>
        </div>
    );
};
export default ResumeDetailsPage;
